mysql_db:
  user: "root"
  host: "localhost"
  password: ""
  port: 3306
  database: "timeoption_"
  table: nightMode

#Placeholders: {prefix}, {action}

lang:
  prefix: "&5NightMode&8> "
  enabled: "&5enabled"
  disabled: "&cdisabled"
  toggle: "{prefix} &aYou {action} &ayour nightmode"
  onlyPlayers: "{prefix} &cEste comando solo puede ser usado por jugadores"
  configReloaded: "{prefix} &aConfig reloaded."
  noPermission: "{prefix} &cYou dont have permission to use this command."