mysql_db:
  user: "root"
  password: ""
  port: 3306
  ip: 127.0.0.1
  database: "timeoption_"
lang:
  enabled: "&5Activado"
  disabled: "&cDesactivado"
  toggled: "&aNight mode:"
  onlyPlayers: "&cokEste comando solo puede ser usado por jugadores"
  configReloaded: "config reloaded"
  noPermission: "You dont have permission"