main: xyz.akriscraft.timeoption.TimeOption
name: TimeOption
version: 1.0
author: NotMeg4_
depend: [PlaceholderAPI]

commands:
  nightmode:
    description: "Toggles your time (Day or Night)."
  nightmodereload:
    description: "Reloads NightMode config."