#Do not touch!
config_Version: 1.0
#Enable if nightmode will use of a MySQL database
mysql_db:
  enabled: false
  user: "root"
  host: "localhost"
  password: ""
  port: 3306
  database: "nigthMode"

#Placeholders: {prefix}, {action}
lang:
  prefix: "&5NightMode&8> "
  enabled: "&5enabled"
  disabled: "&cdisabled"
  toggle: "{prefix} &aYou {action} &ayour nightmode!"
  onlyPlayers: "{prefix} &cThis command can be used only by players!"
  configReloaded: "{prefix} &aConfig reloaded."
  noPermission: "{prefix} &cYou dont have permission to use this command."

#Enable if nightmode will only work on specific worlds
worlds:
  perWorld: false
  enabledWorlds:
    - Lobby